name: Python application deployment

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy databricks bundle"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      
      - name: Deploy Databricks bundle
      - run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
          DATABRICKS_BUNDLE_ENV: development